version: '3'
services:
  gip-app:
      build: .
      container_name: ${APP_CONTAINER_NAME}
      env_file:
      - .env
      ports:
          - "80:80"
      links:
          - ${DB_CONTAINER_NAME}
  gip-db:
      image: mysql:${MYSQL_VERSION}
      restart: always
      container_name: ${DB_CONTAINER_NAME}
      env_file:
      - .env
      command: --default-authentication-plugin=mysql_native_password
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
