version: 2
jobs:
  build:
    machine: true
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: Run docker-compose
          command: |
            docker-compose build
            docker-compose up
      - run:
          name: Check working directory
          command: pwd
