version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
        # - run:
        #  name: Run docker-compose build
        #  command: docker-compose build

      - run:
          name: Install Composer
          command: |
              curl -sS https://getcomposer.org/installer -o composer-setup.php && \
              php composer-setup.php --filename=composer --version=1.8.4 --install-dir=/usr/local/bin && \
              cd /var/myApp/ && \
              composer install && \

      - run:
          name: Laravel unit test
          command: |
            cd myApp
            composer install
            ls -ltr

        #- run: 
            # name: Run docker-compose up 
            # command: docker-compose up -d 
            
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
