version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      #- run:
      #    name: Run docker-compose build
      #    command: docker-compose build
      - run:
          name: Check working directory
          command: pwd
      - run: 
          name: Run docker-compose up
          command: docker-compose up
      #- run:
      #    name: Laravel unit test
      #    command: |

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
