version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Run docker-compose build
          command: docker-compose build
              

      #- run:
      #    name: Laravel unit test
      #    command: |
      #      cd /var/myApp/
      #      ls -ltr 
      #      vendor/bin/phpunit --filter testRegisterSuccessfully UserRegisterTest ./tests/Unit/UserRegisterTest.php
      #      ls -ltr

      - run: 
          name: Run docker-compose up 
          command: docker-compose up -d 
            
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        

