version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Run docker-compose build
          command: docker-compose build 

      - run: 
          name: Run docker-compose up 
          command: docker-compose up -d
      - run:
          name: Delay
          command: sleep 180;
      - run:
          name: Laravel Unit Test
          command: docker exec git-app bash -c 'ls -ltr ; vendor/bin/phpunit' 
                 
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
