version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run docker-compose build
          command: docker-compose build
      - run:
          name: Check working directory
          command: pwd
      - run: 
          name: Run docker-compose up 
          command: docker-compose up -d 
      - run:
          name: change directory
          command: cd myApp
      - run:
          name: List project directory
          command: ls -ltr

      - run:
          name: Laravel unit test
          command: vendor/bin/phpunit 
            
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
