version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run docker-compose build
          command: docker-compose build

      - run:
          name: Install composer
          command: |
            cd myApp
            composer install
 
      - run:
          name: Laravel unit test
          command: |
            ls -ltr
            vendor/bin/phpunit

      - run: 
          name: Run docker-compose up 
          command: docker-compose up -d 
            
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
